2022-06-28 10:21:58.243698 - ERRORE -> HTTPConnectionPool(host='192.168.20.12', port=8082): Max retries exceeded with url: /STAT/EVENTI (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001FED76E0820>, 'Connection to 192.168.20.12 timed out. (connect timeout=None)'))
2022-06-28 10:27:19.313520 - ERRORE -> HTTPConnectionPool(host='192.168.20.12', port=8082): Max retries exceeded with url: /STAT/EVENTI (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001FED7683790>, 'Connection to 192.168.20.12 timed out. (connect timeout=None)'))
2022-06-28 10:32:40.365698 - ERRORE -> HTTPConnectionPool(host='192.168.20.12', port=8082): Max retries exceeded with url: /STAT/EVENTI (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001FED76E1090>, 'Connection to 192.168.20.12 timed out. (connect timeout=None)'))
2022-06-28 10:38:01.435085 - ERRORE -> HTTPConnectionPool(host='192.168.20.12', port=8082): Max retries exceeded with url: /STAT/EVENTI (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001FED76E17E0>, 'Connection to 192.168.20.12 timed out. (connect timeout=None)'))
2022-06-28 10:43:22.453418 - ERRORE -> HTTPConnectionPool(host='192.168.20.12', port=8082): Max retries exceeded with url: /STAT/EVENTI (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001FED76E1F30>, 'Connection to 192.168.20.12 timed out. (connect timeout=None)'))
2022-06-28 10:48:43.486889 - ERRORE -> HTTPConnectionPool(host='192.168.20.12', port=8082): Max retries exceeded with url: /STAT/EVENTI (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001FED76E2680>, 'Connection to 192.168.20.12 timed out. (connect timeout=None)'))
2022-06-28 10:54:04.527063 - ERRORE -> HTTPConnectionPool(host='192.168.20.12', port=8082): Max retries exceeded with url: /STAT/EVENTI (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001FED76E2DD0>, 'Connection to 192.168.20.12 timed out. (connect timeout=None)'))
2022-06-28 10:59:25.550982 - ERRORE -> HTTPConnectionPool(host='192.168.20.12', port=8082): Max retries exceeded with url: /STAT/EVENTI (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001FED76E23B0>, 'Connection to 192.168.20.12 timed out. (connect timeout=None)'))
2022-06-28 11:04:46.599149 - ERRORE -> HTTPConnectionPool(host='192.168.20.12', port=8082): Max retries exceeded with url: /STAT/EVENTI (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001FED76E1C60>, 'Connection to 192.168.20.12 timed out. (connect timeout=None)'))
2022-06-28 11:10:07.646883 - ERRORE -> HTTPConnectionPool(host='192.168.20.12', port=8082): Max retries exceeded with url: /STAT/EVENTI (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001FED76E1330>, 'Connection to 192.168.20.12 timed out. (connect timeout=None)'))
2022-06-28 11:15:28.715690 - ERRORE -> HTTPConnectionPool(host='192.168.20.12', port=8082): Max retries exceeded with url: /STAT/EVENTI (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001FED76E1000>, 'Connection to 192.168.20.12 timed out. (connect timeout=None)'))
2022-06-28 11:20:49.757962 - ERRORE -> HTTPConnectionPool(host='192.168.20.12', port=8082): Max retries exceeded with url: /STAT/EVENTI (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001FED76E0D90>, 'Connection to 192.168.20.12 timed out. (connect timeout=None)'))
2022-06-28 11:26:10.782866 - ERRORE -> HTTPConnectionPool(host='192.168.20.12', port=8082): Max retries exceeded with url: /STAT/EVENTI (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001FED76E3520>, 'Connection to 192.168.20.12 timed out. (connect timeout=None)'))
2022-06-28 11:31:31.830182 - ERRORE -> HTTPConnectionPool(host='192.168.20.12', port=8082): Max retries exceeded with url: /STAT/EVENTI (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001FED76E1090>, 'Connection to 192.168.20.12 timed out. (connect timeout=None)'))
2022-06-28 11:36:52.864857 - ERRORE -> HTTPConnectionPool(host='192.168.20.12', port=8082): Max retries exceeded with url: /STAT/EVENTI (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001FED76E16F0>, 'Connection to 192.168.20.12 timed out. (connect timeout=None)'))
2022-06-28 11:42:13.916045 - ERRORE -> HTTPConnectionPool(host='192.168.20.12', port=8082): Max retries exceeded with url: /STAT/EVENTI (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001FED76E1AB0>, 'Connection to 192.168.20.12 timed out. (connect timeout=None)'))
2022-06-28 11:47:34.939966 - ERRORE -> HTTPConnectionPool(host='192.168.20.12', port=8082): Max retries exceeded with url: /STAT/EVENTI (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001FED76E2C20>, 'Connection to 192.168.20.12 timed out. (connect timeout=None)'))
2022-06-28 11:52:55.995601 - ERRORE -> HTTPConnectionPool(host='192.168.20.12', port=8082): Max retries exceeded with url: /STAT/EVENTI (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001FED76E23B0>, 'Connection to 192.168.20.12 timed out. (connect timeout=None)'))
2022-06-28 11:58:17.027071 - ERRORE -> HTTPConnectionPool(host='192.168.20.12', port=8082): Max retries exceeded with url: /STAT/EVENTI (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001FED76E24A0>, 'Connection to 192.168.20.12 timed out. (connect timeout=None)'))
2022-06-28 12:03:38.110376 - ERRORE -> HTTPConnectionPool(host='192.168.20.12', port=8082): Max retries exceeded with url: /STAT/EVENTI (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001FED7683190>, 'Connection to 192.168.20.12 timed out. (connect timeout=None)'))
2022-06-28 12:08:59.167453 - ERRORE -> HTTPConnectionPool(host='192.168.20.12', port=8082): Max retries exceeded with url: /STAT/EVENTI (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001FED76E2AA0>, 'Connection to 192.168.20.12 timed out. (connect timeout=None)'))
2022-06-28 12:14:20.219069 - ERRORE -> HTTPConnectionPool(host='192.168.20.12', port=8082): Max retries exceeded with url: /STAT/EVENTI (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001FED76E25F0>, 'Connection to 192.168.20.12 timed out. (connect timeout=None)'))
2022-06-28 12:19:41.290384 - ERRORE -> HTTPConnectionPool(host='192.168.20.12', port=8082): Max retries exceeded with url: /STAT/EVENTI (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001FED76E1E10>, 'Connection to 192.168.20.12 timed out. (connect timeout=None)'))
2022-06-28 12:25:02.359299 - ERRORE -> HTTPConnectionPool(host='192.168.20.12', port=8082): Max retries exceeded with url: /STAT/EVENTI (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001FED76E1480>, 'Connection to 192.168.20.12 timed out. (connect timeout=None)'))
2022-06-28 12:30:23.451536 - ERRORE -> HTTPConnectionPool(host='192.168.20.12', port=8082): Max retries exceeded with url: /STAT/EVENTI (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001FED76E0BE0>, 'Connection to 192.168.20.12 timed out. (connect timeout=None)'))
2022-06-28 12:35:44.500814 - ERRORE -> HTTPConnectionPool(host='192.168.20.12', port=8082): Max retries exceeded with url: /STAT/EVENTI (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001FED76E3C70>, 'Connection to 192.168.20.12 timed out. (connect timeout=None)'))
2022-06-28 12:41:05.550347 - ERRORE -> HTTPConnectionPool(host='192.168.20.12', port=8082): Max retries exceeded with url: /STAT/EVENTI (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001FED76E0FA0>, 'Connection to 192.168.20.12 timed out. (connect timeout=None)'))
2022-06-28 12:46:26.613231 - ERRORE -> HTTPConnectionPool(host='192.168.20.12', port=8082): Max retries exceeded with url: /STAT/EVENTI (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001FED76E08B0>, 'Connection to 192.168.20.12 timed out. (connect timeout=None)'))
2022-06-28 12:51:47.662072 - ERRORE -> HTTPConnectionPool(host='192.168.20.12', port=8082): Max retries exceeded with url: /STAT/EVENTI (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001FED76E1540>, 'Connection to 192.168.20.12 timed out. (connect timeout=None)'))
2022-06-28 12:57:08.720343 - ERRORE -> HTTPConnectionPool(host='192.168.20.12', port=8082): Max retries exceeded with url: /STAT/EVENTI (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001FED76E2E60>, 'Connection to 192.168.20.12 timed out. (connect timeout=None)'))
2022-06-28 13:02:29.761833 - ERRORE -> HTTPConnectionPool(host='192.168.20.12', port=8082): Max retries exceeded with url: /STAT/EVENTI (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001FED76E2590>, 'Connection to 192.168.20.12 timed out. (connect timeout=None)'))
2022-06-28 13:07:50.816909 - ERRORE -> HTTPConnectionPool(host='192.168.20.12', port=8082): Max retries exceeded with url: /STAT/EVENTI (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001FED76E2B90>, 'Connection to 192.168.20.12 timed out. (connect timeout=None)'))
2022-06-28 13:13:11.870664 - ERRORE -> HTTPConnectionPool(host='192.168.20.12', port=8082): Max retries exceeded with url: /STAT/EVENTI (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001FED76839D0>, 'Connection to 192.168.20.12 timed out. (connect timeout=None)'))
2022-06-28 13:18:32.919428 - ERRORE -> HTTPConnectionPool(host='192.168.20.12', port=8082): Max retries exceeded with url: /STAT/EVENTI (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001FED76E2E30>, 'Connection to 192.168.20.12 timed out. (connect timeout=None)'))
2022-06-28 13:23:53.963581 - ERRORE -> HTTPConnectionPool(host='192.168.20.12', port=8082): Max retries exceeded with url: /STAT/EVENTI (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001FED76E2380>, 'Connection to 192.168.20.12 timed out. (connect timeout=None)'))
2022-06-28 13:29:15.000057 - ERRORE -> HTTPConnectionPool(host='192.168.20.12', port=8082): Max retries exceeded with url: /STAT/EVENTI (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001FED76E2020>, 'Connection to 192.168.20.12 timed out. (connect timeout=None)'))
2022-06-28 13:34:36.055394 - ERRORE -> HTTPConnectionPool(host='192.168.20.12', port=8082): Max retries exceeded with url: /STAT/EVENTI (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001FED76E1300>, 'Connection to 192.168.20.12 timed out. (connect timeout=None)'))
2022-06-28 13:39:57.131990 - ERRORE -> HTTPConnectionPool(host='192.168.20.12', port=8082): Max retries exceeded with url: /STAT/EVENTI (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001FED76E3B20>, 'Connection to 192.168.20.12 timed out. (connect timeout=None)'))
2022-06-28 13:45:18.166369 - ERRORE -> HTTPConnectionPool(host='192.168.20.12', port=8082): Max retries exceeded with url: /STAT/EVENTI (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001FED76E0D90>, 'Connection to 192.168.20.12 timed out. (connect timeout=None)'))
2022-06-28 13:50:39.210331 - ERRORE -> HTTPConnectionPool(host='192.168.20.12', port=8082): Max retries exceeded with url: /STAT/EVENTI (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001FED76E0D00>, 'Connection to 192.168.20.12 timed out. (connect timeout=None)'))
2022-06-28 13:56:00.251299 - ERRORE -> HTTPConnectionPool(host='192.168.20.12', port=8082): Max retries exceeded with url: /STAT/EVENTI (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001FED76E2200>, 'Connection to 192.168.20.12 timed out. (connect timeout=None)'))
2022-06-28 14:01:21.287003 - ERRORE -> HTTPConnectionPool(host='192.168.20.12', port=8082): Max retries exceeded with url: /STAT/EVENTI (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001FED76E1B10>, 'Connection to 192.168.20.12 timed out. (connect timeout=None)'))
2022-06-28 14:06:42.304853 - ERRORE -> HTTPConnectionPool(host='192.168.20.12', port=8082): Max retries exceeded with url: /STAT/EVENTI (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001FED76E0820>, 'Connection to 192.168.20.12 timed out. (connect timeout=None)'))
2022-06-28 14:12:03.347649 - ERRORE -> HTTPConnectionPool(host='192.168.20.12', port=8082): Max retries exceeded with url: /STAT/EVENTI (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001FED76E2D10>, 'Connection to 192.168.20.12 timed out. (connect timeout=None)'))
2022-06-28 14:17:24.397050 - ERRORE -> HTTPConnectionPool(host='192.168.20.12', port=8082): Max retries exceeded with url: /STAT/EVENTI (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001FED76E2D40>, 'Connection to 192.168.20.12 timed out. (connect timeout=None)'))
2022-06-28 14:22:45.448979 - ERRORE -> HTTPConnectionPool(host='192.168.20.12', port=8082): Max retries exceeded with url: /STAT/EVENTI (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001FED76E2BC0>, 'Connection to 192.168.20.12 timed out. (connect timeout=None)'))
2022-06-28 14:28:06.500726 - ERRORE -> HTTPConnectionPool(host='192.168.20.12', port=8082): Max retries exceeded with url: /STAT/EVENTI (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001FED76E2B90>, 'Connection to 192.168.20.12 timed out. (connect timeout=None)'))
2022-06-28 14:33:27.524654 - ERRORE -> HTTPConnectionPool(host='192.168.20.12', port=8082): Max retries exceeded with url: /STAT/EVENTI (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001FED76E1CC0>, 'Connection to 192.168.20.12 timed out. (connect timeout=None)'))
2022-06-28 14:38:48.558139 - ERRORE -> HTTPConnectionPool(host='192.168.20.12', port=8082): Max retries exceeded with url: /STAT/EVENTI (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001FED76E1A50>, 'Connection to 192.168.20.12 timed out. (connect timeout=None)'))
2022-06-28 14:44:09.599811 - ERRORE -> HTTPConnectionPool(host='192.168.20.12', port=8082): Max retries exceeded with url: /STAT/EVENTI (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001FED76E1210>, 'Connection to 192.168.20.12 timed out. (connect timeout=None)'))
2022-06-28 14:49:11.616660 - ERRORE -> HTTPConnectionPool(host='192.168.20.12', port=8082): Max retries exceeded with url: /STAT/EVENTI (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FED7683190>: Failed to establish a new connection: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione'))
2022-06-28 15:19:11.778357 - ERRORE -> Invalid \escape: line 413 column 21 (char 8619)
2022-06-28 15:24:11.784292 - ERRORE -> Invalid \escape: line 413 column 21 (char 8619)
2022-06-28 15:29:11.797718 - ERRORE -> Invalid \escape: line 413 column 21 (char 8619)
2022-06-28 15:34:11.811905 - ERRORE -> Invalid \escape: line 413 column 21 (char 8619)
2022-06-28 15:44:34.724036 - ERRORE -> Invalid \escape: line 413 column 21 (char 8619)
